Prepared the routing
WildCodeSchool/lyon-js-react-march21-g1-p2 pull request #27
Opened 2021-04-09 16:32 UTC by DuboisCecile

2021-04-09 23:48 UTC, BuG-Dev-Joris approved these changes
Really great work cecile

2021-04-10 09:18 UTC, Herelius commented
Nice 👍

2021-04-10 09:18 UTC, Herelius commented
Nice

2021-04-10 09:22 UTC, Herelius approved these changes
Nice

2021-04-10 14:27 UTC, So-G commented
super 👌

2021-04-10 14:29 UTC, So-G approved these changes

2021-04-12 09:09 UTC, ComicScrip requested changes

2021-04-12 09:09 UTC, ComicScrip commented on .gitignore
> +.github
Le .github ne devrait pas être dans le gitignore car on veut le versionner

2021-04-12 09:09 UTC, ComicScrip commented on src/components/Header.js
> +    <header>
Attention, avec la structure actuelle, vous avez un header dans un main

2021-04-12 09:09 UTC, ComicScrip commented on src/components/HeaderOrder.js
> +export default function HeaderOrder() {
préférer faire un seul composant header qui va rendre quelque chose de différent si on est sur une page en particulier.

Pour connaître l'url courante, on peut utiliser https://reactrouter.com/web/api/Hooks/uselocation

2021-04-12 09:33 UTC, merged