Ingredients : increment/decrement de quantities
WildCodeSchool/lyon-js-react-march21-g1-p2 pull request #49
Opened 2021-04-16 12:48 UTC by DuboisCecile

Still have a problem with line 323 of CustomizedFoodPage.js :
With {ingr.quantity} the quantity stays to 0, despite the fact that the array of ingredients is updated
When I try to use a state, it changes all the quantities (of all ingredients) each time I add 1 portion.

(Decrement is not working either, but it is probably because the quantity is stuck to 0, and it shouldn't decrement when the quantity is 0. So it basically does nothing...)

2021-04-17 15:13 UTC, DuboisCecile commented
Problem fixed !

We can now add and remove ingredients : the quantities are updated and the image layer of each ingredient is added on the pizza, or removed when quantity of this ingredient = 0

2021-04-19 12:20 UTC, ComicScrip requested changes

2021-04-19 12:20 UTC, ComicScrip commented on src/components/PizzaChange.js
> +        {ChosenIngredientsList.map((ingr) =>
camelCase, please :)
PascalCase should be used for react components only

2021-04-19 12:20 UTC, ComicScrip commented on src/screens/CustomizedFoodPage.js
> +        ingredToUpdate[0].quantity += 1;
mutations are forbidden on react state data

2021-04-19 12:20 UTC, ComicScrip commented on src/screens/CustomizedFoodPage.js
> +        ingredToUpdate[0].quantity += 1;
prefer mapping over the array in the state to create a new version with the quantity updated

2021-04-19 12:23 UTC, ComicScrip commented on src/screens/CustomizedFoodPage.js
> +        ingredToUpdate[0].quantity += 1;
or use https://immerjs.github.io/immer/#quick-example

2021-04-21 09:31 UTC, ComicScrip commented
@DuboisCecile can I merge this or do you still have bugs ?

2021-04-21 10:08 UTC, DuboisCecile commented
Yes, you can merge it, (yesterday's bugs were on another branch, for a future PR)
Thanks !

2021-04-21 11:36 UTC, merged